#!/usr/bin/env python3
# BX-TREES (AR34 BX, 2026-10-02): the web's copy of the tree asset set (public/models/bxtrees), read by src/city/bxTrees.js
# behind ?bxtrees=1.
#
#   python3 tools/ar34/bxtrees/web_pack.py [--trees P_m,...] [--assets /data0/projectnyc_aux/assets/bxtrees] [--out public/models/bxtrees]
#
# Per tree <id>.bin (one gzip member): a little-endian uint32 header length, the JSON header, then the arrays (4-byte aligned)
# of three levels, the web's own split of the asset LODs:
#   w0   near (the web's LOD0, to its 90 m swap): the tree regrown by treegen.py (deterministic per seed) with limbs to the
#        tertiaries (no twigs) and at most CAP leaf cards (a random subset scaled up by sqrt(n / CAP): the crown's leaf area
#        and its clumps kept, the triangles cut ~2-6x from the film's lod0)
#   w1   the asset's lod1 (limbs to the secondaries, a quarter of the leaves at twice the size), 90-150 m
#   imp  the asset's impostor (three baked cards), past 150 m
# Arrays per mesh: positions int16 over the mesh's box, normals int8, leaf uv uint16 (0..1), bark / impostor uv float32
# (the bark repeats), the leaves' crown-depth shade uint8, bark / impostor indices uint32; the leaves' indices are implicit
# (8 vertices and 6 triangles a card, generated by the loader).
# Textures (the same scans as the film's, smaller): <F>_leaf_col.webp / _nrm.webp (1024 px), bark_<key>_col.jpg / _nrm.jpg
# (1024 px), imp_<id>.webp.
import gzip, json, math, os, shutil, sys
import numpy as np
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import treegen as tg

def opt(n, d=None):
    a = sys.argv
    if '--' + n in a:
        i = a.index('--' + n)
        return a[i + 1] if i + 1 < len(a) and not a[i + 1].startswith('--') else '1'
    return d
ASSETS = opt('assets', '/data0/projectnyc_aux/assets/bxtrees')
OUT = opt('out', os.path.join(HERE, '..', '..', '..', 'public', 'models', 'bxtrees'))
OUT = os.path.abspath(OUT)
os.makedirs(OUT, exist_ok=True)
CAP = int(opt('cap', '9000'))
LM = json.load(open(f'{ASSETS}/tex/leaves.json'))['species']
BOX = {'P_m': (12.6, 10.4), 'P_y': (9.4, 5.9), 'H_m': (10.0, 10.0), 'H_y': (8.4, 6.4), 'Q_m': (12.0, 10.3), 'Q_y': (9.9, 6.1),
       'Z_m': (13.1, 11.0), 'Z_y': (9.7, 6.4), 'R_m': (10.7, 9.3), 'R_y': (8.4, 5.6), 'L_m': (12.2, 10.2), 'L_y': (10.2, 6.6),
       'M_m': (12.9, 10.9), 'M_y': (9.6, 6.6), 'S_m': (12.4, 10.6),
       'Y_m': (10.3, 8.0), 'X_m': (7.3, 7.3), 'W_m': (6.9, 6.1), 'P_m2': (12.25, 10.4), 'H_m2': (11.0, 10.6)}
SEED = {'P': 101, 'H': 202, 'Q': 404, 'Z': 909, 'R': 303, 'L': 606, 'M': 505, 'S': 1010, 'Y': 808, 'X': 1111, 'W': 1212}
BARK_OF = {'P': 'plane', 'H': 'willow', 'Q': 'oak', 'Z': 'zelkova', 'R': 'pear', 'L': 'linden', 'M': 'maple', 'S': 'linden', 'Y': 'cherry', 'X': 'cherry', 'W': 'oak'}
TREES = (opt('trees') or 'P_m,P_y,H_m,H_y,Q_m,Q_y,Z_m,Z_y,R_m,R_y,L_m,L_y,M_m,M_y,S_m,Y_m,X_m,W_m,P_m2,H_m2').split(',')

class Pack:
    def __init__(self):
        self.parts, self.off, self.head = [], 0, {}
    def add(self, arr):
        b = np.ascontiguousarray(arr).tobytes()
        pad = (-len(b)) % 4
        o = self.off
        self.parts.append(b + b'\0' * pad); self.off += len(b) + pad
        return [o, len(b)]
    def mesh(self, M, leaf):
        P = M['P'].astype(np.float64)
        lo, hi = P.min(0), P.max(0)
        q = np.round((P - lo) / np.maximum(hi - lo, 1e-6) * 65535 - 32768).clip(-32768, 32767).astype(np.int16)
        n = np.round(M['N'] * 127).clip(-127, 127).astype(np.int8)
        h = {'nv': int(len(P)), 'box': [lo.tolist(), hi.tolist()], 'pos': self.add(q), 'nrm': self.add(n)}
        if leaf:
            h['uv'] = self.add(np.round(M['UV'] * 65535).clip(0, 65535).astype(np.uint16))
            h['shade'] = self.add(np.round(M['C'] * 255).clip(0, 255).astype(np.uint8))
            h['cards'] = int(len(P) // 8)
        else:
            h['uv'] = self.add(M['UV'].astype(np.float32))
            h['idx'] = self.add(M['I'].astype(np.uint32).reshape(-1)); h['ni'] = int(M['I'].size)
        return h
    def write(self, path):
        hj = json.dumps(self.head).encode()
        hj += b' ' * ((-len(hj)) % 4)
        data = np.uint32(len(hj)).tobytes() + hj + b''.join(self.parts)
        with gzip.open(path, 'wb', compresslevel=6) as f: f.write(data)
        return len(data)

man = {}
try: man = json.load(open(f'{OUT}/bxtrees.json'))
except Exception: man = {}
man.setdefault('trees', {})
for tid in TREES:
    F, size = tid.split('_')
    H, W = BOX[tid]
    tree = tg.build(F, size, H, W, SEED[F] + {'m': 0, 'y': 17, 'm2': 4242}.get(size, 17), LM[F])
    n = len(tree.leafs['pos'])
    rng = np.random.default_rng(11)
    if n > CAP:
        sel = np.sort(rng.choice(n, CAP, replace=False)); k = math.sqrt(n / CAP)
        k = min(k, 1.6)   # (a near leaf no more than 1.6x its size: past that the coverage is let go)
    else:
        sel, k = None, 1.0
    b0 = tg.tube_mesh(tree, lvl_max=3, sides_k=0.8, tile=0.9)
    l0 = tg.leaf_mesh(tree, sel=sel, scale=k)
    # w1: limbs to the secondaries, CAP1 cards (the web's 90-150 m band; the asset's lod1 keeps a quarter of all leaves, too
    # many for the web's band on the dense species)
    CAP1 = int(opt('cap1', '1800'))
    sel1 = np.sort(rng.choice(n, min(n, CAP1), replace=False))
    b1 = tg.tube_mesh(tree, lvl_max=2, sides_k=0.55, ring_step=2, tile=0.9)
    l1 = tg.leaf_mesh(tree, sel=sel1, scale=math.sqrt(n / max(1, len(sel1))), fold_deg=6)
    pk = Pack()
    pk.head = {'id': tid, 'F': F, 'size': size, 'H': H, 'W': W, 'bark': BARK_OF[F], 'leafScale0': round(k, 3),
               'w0': {'bark': pk.mesh(b0, False), 'leaf': pk.mesh(l0, True)},
               'w1': {'bark': pk.mesh(b1, False), 'leaf': pk.mesh(l1, True)}}
    if os.path.exists(f'{ASSETS}/npz/{tid}_imp.npz'):
        Zi = np.load(f'{ASSETS}/npz/{tid}_imp.npz')
        pk.head['imp'] = pk.mesh({a: Zi[f'imp_{a}'] for a in ('P', 'N', 'UV', 'I')}, False)
        Image.open(f'{ASSETS}/imp/{tid}.png').save(f'{OUT}/imp_{tid}.webp', quality=88, method=6)
    raw = pk.write(f'{OUT}/{tid}.bin')
    tris = {lv: {'bark': pk.head[lv]['bark']['ni'] // 3, 'leaf': pk.head[lv]['leaf']['cards'] * 6} for lv in ('w0', 'w1')}
    man['trees'][tid] = {'file': f'{tid}.bin', 'bytes': os.path.getsize(f'{OUT}/{tid}.bin'), 'raw': raw, 'tris': tris, 'leaf': F, 'bark': BARK_OF[F],
                         'imp': f'imp_{tid}.webp' if 'imp' in pk.head else None}
    print(tid, man['trees'][tid])
# textures
for F in sorted({t.split('_')[0] for t in man['trees']}):
    for s in ('col', 'nrm'):
        shutil.copyfile(f'{ASSETS}/tex/{F}_leaf_{s}.webp', f'{OUT}/{F}_leaf_{s}.webp')
for key in sorted({v['bark'] for v in man['trees'].values()}):
    for s in ('col', 'nrm'):
        shutil.copyfile(f'{ASSETS}/web/bark_{key}_{s}.jpg', f'{OUT}/bark_{key}_{s}.jpg')
man['version'] = 1
man['note'] = 'BX-TREES asset set, web copy (tools/ar34/bxtrees/web_pack.py); see NOTICE.md'
json.dump(man, open(f'{OUT}/bxtrees.json', 'w'), indent=1)
tot = sum(os.path.getsize(os.path.join(OUT, f)) for f in os.listdir(OUT))
print('total MB', round(tot / 1e6, 2))
