// Generates boundlessjs/src/city/hptSignOutline.js: the Pepsi-Cola letters' outline loops and the neon's line, traced from the
// stroke field (hptSignStrokes.js + hptSignTrace.js), so the page does no tracing at run time.
//   node boundlessjs/tools/ar33/hpt/gen_outline.mjs
import path from 'node:path';
import fs from 'node:fs';
import { pathToFileURL } from 'node:url';
const here = path.resolve('boundlessjs/src/city');
const { strokeLines } = await import(pathToFileURL(path.join(here, 'hptSignStrokes.js')).href);
const T = await import(pathToFileURL(path.join(here, 'hptSignTrace.js')).href);
const lines = strokeLines();
const fld = T.strokeField(lines, { U0: -1, V0: -2.2, Wm: 42, Hm: 17.2, px: 50 });
const flat = (loops) => loops.map((l) => '[' + l.map(([u, v]) => `${u.toFixed(3)},${v.toFixed(3)}`).join(',') + ']').join(',\n  ');
const letters = T.traceField(fld, 0, 0.005);
const neon = T.traceField(fld, 0.07, 0.01);
const out = `// GENERATED by boundlessjs/tools/ar33/hpt/gen_outline.mjs from hptSignStrokes.js: do not edit by hand.
// The Pepsi-Cola letters' outline loops (LETTER_LOOPS, 5 mm) and the neon tube's line 7 cm outside them (NEON_LOOPS, 1 cm),
// each loop a flat [u, v, u, v, ...] in metres on the sign (u from the P's curl, v up from the swash).
export const LETTER_LOOPS = [
  ${flat(letters)}
];
export const NEON_LOOPS = [
  ${flat(neon)}
];
`;
fs.writeFileSync(path.join(here, 'hptSignOutline.js'), out);
console.log('letters', letters.length, 'loops', letters.reduce((s, l) => s + l.length, 0), 'points; neon', neon.length, 'loops', neon.reduce((s, l) => s + l.length, 0), 'points;', (out.length / 1024).toFixed(0), 'KB');
